object FrmFinalizaVenda: TFrmFinalizaVenda
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'Finalizar Venda'
  ClientHeight = 625
  ClientWidth = 905
  Color = clBtnFace
  Constraints.MaxHeight = 625
  Constraints.MaxWidth = 905
  Constraints.MinHeight = 625
  Constraints.MinWidth = 905
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clBlack
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  KeyPreview = True
  Position = poScreenCenter
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  TextHeight = 15
  object pnlFundo: TPanel
    Left = 0
    Top = 0
    Width = 905
    Height = 625
    Align = alClient
    BevelOuter = bvNone
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -15
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 0
    object pnlTitulo: TJvPanel
      AlignWithMargins = True
      Left = 3
      Top = 3
      Width = 899
      Height = 40
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -15
      HotTrackFont.Name = 'Segoe UI'
      HotTrackFont.Style = []
      Align = alTop
      Alignment = taLeftJustify
      BevelOuter = bvNone
      BorderWidth = 5
      Caption = ' Finalizar Venda'
      Color = 4142595
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -24
      Font.Name = 'Segoe UI'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      OnMouseDown = pnlTituloMouseDown
      object btnClose: TAeroSpeedButton
        AlignWithMargins = True
        Left = 861
        Top = 8
        Width = 30
        Height = 24
        Hint = 'Fechar '
        Align = alRight
        Glyph.Data = {
          360C0000424D360C000000000000360000002800000020000000200000000100
          180000000000000C0000C40E0000C40E00000000000000000000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8
          F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FF
          F8F8FFF8F8FFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8
          F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FF
          F8F8FFF8F8FFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFFFE
          FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFFCFCFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFBFBFFF8F8FFF9
          F9FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF8F8FFFCFCFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF8
          F8FFF9F9FFFFFFFFFFFFFFFFFFFFFFFFFFF9F9FFF8F8FFF9F9FFFEFEFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9
          F9FFF8F8FFF9F9FFFFFFFFFFFFFFF9F9FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
          FEFFF9F9FFF8F8FFF9F9FFF9F9FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFEFEFFF9F9FFF8F8FFF8F8FFFAFAFFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFF9F9FFF8F8FFF8F8FFF9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFF9F9FFF8F8FFF9F9FFF8F8FFF8F8FFF9F9FFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9
          F9FFF8F8FFF9F9FFFEFEFFFEFEFFF9F9FFF8F8FFF9F9FFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFF9F9FFF8
          F8FFF9F9FFFEFEFFFFFFFFFFFFFFFEFEFFF9F9FFF8F8FFF9F9FFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFCFCFFF8F8FFF9
          F9FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF8F8FFFDFDFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFFE
          FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFFDFDFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8
          F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FF
          F8F8FFF8F8FFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8
          F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FF
          F8F8FFF8F8FFF8F8FFF8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
        ParentShowHint = False
        ShowHint = True
        OnClick = btnCloseClick
        ExplicitLeft = 783
        ExplicitTop = 3
        ExplicitHeight = 30
      end
    end
    object pnlBotoes: TJvPanel
      AlignWithMargins = True
      Left = 3
      Top = 569
      Width = 899
      Height = 53
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -15
      HotTrackFont.Name = 'Segoe UI'
      HotTrackFont.Style = []
      Align = alBottom
      Alignment = taLeftJustify
      BevelOuter = bvNone
      Color = 4142595
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -40
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 1
      object btnFinalizar: TAeroSpeedButton
        AlignWithMargins = True
        Left = 661
        Top = 3
        Width = 235
        Height = 47
        Hint = 'Salvar registro'
        Align = alRight
        Caption = 'Finalizar'
        Glyph.Data = {
          E61D0000424DE61D000000000000360000002800000032000000320000000100
          180000000000B01D000074120000741200000000000000000000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFF
          FDFDFFFDFDFFFDFDFFFDFDFFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFEFEFFFBFBFFF9F9FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8
          FFF8F8FFF8F8FFF8F8FFF9F9FFFBFBFFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF9F9
          FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8
          F8FFF8F8FFF8F8FFF8F8FFF9F9FFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF9F9FFF8F8FFF8F8FFF8F8FFF8F8FFF8
          F8FFF8F8FFF8F8FFF9F9FFF9F9FFF9F9FFF9F9FFF8F8FFF8F8FFF8F8FFF8F8FF
          F8F8FFF8F8FFF8F8FFF9F9FFFDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
          FEFFFAFAFFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFFAFAFFFCFCFFFEFEFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFFCFCFFFAFAFFF8F8FFF8F8FFF8F8
          FFF8F8FFF8F8FFFAFAFFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFDFFF9F9FFF8F8FFF8F8FF
          F8F8FFF8F8FFFBFBFFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFFBFBFFF8F8FFF8F8FFF8F8FFF8
          F8FFF9F9FFFDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFDFDFFF8F8FFF8F8FFF8F8FFF8F8FFFAFAFFFEFEFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFFAFAFFF8F8FFF8F8FFF8F8FFF8F8FF
          FDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFE
          FFF8F8FFF8F8FFF8F8FFF8F8FFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF8F8FFF8F8FFF8F8FFF8F8FFFEFEFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF8F8FFF8F8FFF8
          F8FFFDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFDFDFFF8F8FFF8F8FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFAFAFFF8F8FFF8F8FFF8F8FFFDFDFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFDFDFFF8F8FFF8F8FFF8F8FFFAFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FCFCFFF8F8FFF8F8FFF8F8FFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFF
          F8F8FFF8F8FFF8F8FFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9F9FFF8F8FFF8F8
          FFFAFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFAFFF8F8FFF8F8
          FFF9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF8F8FFF8F8FFF8F8FFFEFEFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFEFEFFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF8F8FFF8F8FFF8F8FFFCFCFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFF9F9FFF8F8FFF8F8FFFBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF9F9
          FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFBFBFFF8F8FFF8F8FFF9F9FFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFDFFF8F8FF
          F8F8FFF8F8FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF8F8FFF8F8FFF9F9FFFEFEFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFEFEFFF8F8FFF8F8FFF8F8FFFDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFFF8F8FFF8F8FFFAFAFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFEFEFFF9F9FFF8F8FFF8F8FFF8F8FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFA
          FFF8F8FFF8F8FFFBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF9F9FFF8F8FFF8F8FFFCFCFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF8F8FF
          F8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF8F8FFF8F8FFF9
          F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFF8F8FFF8F8FFF8F8FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF8F8FFF8F8FFF8F8FFFCFCFFFCFC
          FFF8F8FFF8F8FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF8F8FFF8F8FFF8F8FFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF8F8FFF8F8FF
          F8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFEFEFFF9F9FFF8F8FFF8F8FFF8F8FFFCFCFFFFFFFFFFFFFFFCFCFFF8F8FFF8
          F8FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFF8F8FFF8F8FFF8F8FFFEFEFFFFFFFFFFFFFFFFFFFFFFFF
          0000FFFFFFFFFFFFFFFFFFFFFFFFFFFDFDFFF8F8FFF8F8FFF9F9FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF8F8FFF8
          F8FFF8F8FFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF8F8FFF8F8FFF8F8FF
          F9F9FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFF9F9FFF8F8FFF8F8FFFDFDFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFDFDFFF8F8FFF8F8FFF9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF8F8FFF8F8FFF8F8FFFBFBFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF8F8FFF8F8FFF8F8FFF9F9FFFEFE
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9F9FFF8F8FFF8
          F8FFFDFDFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFD
          FDFFF8F8FFF8F8FFF9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFAFAFFF8F8FFF8F8FFF8F8FFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFCFCFFF8F8FFF8F8FFF8F8FFF9F9FFFEFEFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9F9FFF8F8FFF8F8FFFDFDFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFDFDFFF8F8FFF8F8FF
          F9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9
          FFF8F8FFFBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFCFCFFF8F8FFF8F8FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFF9F9FFF8F8FFF8F8FFFEFEFFFFFFFFFFFFFFFFFFFFFFFF
          0000FFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF8F8FFF8F8FFF8F8FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFFCFCFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FCFCFFF8F8FFF8F8FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFF8F8FFF8F8FFF8F8FFFEFEFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFF8F8FFF8F8FFF8F8FFFEFEFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF8F8
          FFF8F8FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFFFFFFFFFEFEFFF8F8FFF8F8FFF8
          F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFF9F9FFF8F8FFF8F8FFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFFF8F8FFF8F8FFF8
          F8FFF9F9FFFEFEFFFFFFFFFFFFFFFFFFFFFAFAFFF8F8FFFAFAFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFFF8F8FF
          F8F8FFFAFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFFF8F8FFF8F8FFF8F8FFF9F9FF
          FEFEFFFFFFFFFFFFFFFFFFFFFAFAFFFBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFDFFF8F8FFF8F8FFF8F8FFFEFE
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFBFBFFF8F8FFF8F8FFF8F8FFF9F9FFFEFEFFFFFF
          FFFFFFFFFFFFFFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFF9F9FFF8F8FFF8F8FFFBFBFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFBFBFFF8F8FFF8F8FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFCFCFFF8F8FFF8F8FFF8F8FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFBFBFFF8F8FFF8F8FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          F9F9FFF8F8FFF8F8FFFAFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFF
          F8F8FFF8F8FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF8F8FFF8F8
          FFF8F8FFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFFF8F8FFF8F8
          FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFAFFF8F8FFF8F8FFF8F8FFFD
          FDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF8F8FFF8F8FFF8F8FFFB
          FBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF8F8FFF8F8FFF8F8FFFDFDFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD
          FDFFFEFEFFFFFFFFFFFFFFFFFFFFFBFBFFF8F8FFFAFAFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFDFDFFF8F8FFF8F8FFF8F8FFF8F8FFFCFCFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF8F8FFF9F9FFFEFEFF
          FFFFFFFFFFFFFFFFFFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFDFDFFF8F8FFF8F8FFF8F8FFF8F8FFFAFAFFFEFEFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFEFEFFFAFAFFF8F8FFF8F8FFF8F8FFF9F9FFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFDFFF9
          F9FFF8F8FFF8F8FFF8F8FFF8F8FFFBFBFFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFFBFBFFF8F8
          FFF8F8FFF8F8FFF8F8FFF9F9FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFFAFAFFF8F8FF
          F8F8FFF8F8FFF8F8FFF8F8FFFAFAFFFCFCFFFEFEFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFEFEFFFCFCFFFAFAFFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFFA
          FAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF8F8FFF8F8FFF8F8
          FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF9F9FFF9F9FFF9F9FFF9F9FFF8F8FFF8
          F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF9F9FFFDFDFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF9F9FFF8F8FFF8F8FFF8
          F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FF
          F8F8FFF9F9FFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFDFFFBFBFFF9F9FFF8F8FFF8F8FF
          F8F8FFF8F8FFF8F8FFF8F8FFF8F8FFF8F8FFFAFAFFFBFBFFFDFDFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFFDFDFFFDFDFFFDFD
          FFFDFDFFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000}
        ParentShowHint = False
        ShowHint = True
        OnClick = btnFinalizarClick
        ExplicitLeft = 568
      end
    end
    object pnlValores: TPanel
      AlignWithMargins = True
      Left = 3
      Top = 398
      Width = 899
      Height = 165
      Align = alBottom
      BevelOuter = bvNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 2
      object pnlTempoDecorrido: TJvGroupBox
        AlignWithMargins = True
        Left = 3
        Top = 3
        Width = 470
        Height = 159
        Align = alLeft
        Caption = 'Tempo decorrido'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -15
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
        object Label7: TLabel
          AlignWithMargins = True
          Left = 8
          Top = 64
          Width = 145
          Height = 18
          AutoSize = False
          Caption = 'Entrada................:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -15
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label9: TLabel
          AlignWithMargins = True
          Left = 8
          Top = 88
          Width = 145
          Height = 18
          AutoSize = False
          Caption = 'Sa'#237'da...................:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -15
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object lblEntrada: TLabel
          Left = 159
          Top = 64
          Width = 5
          Height = 21
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -17
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblSaida: TLabel
          Left = 159
          Top = 88
          Width = 200
          Height = 18
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -17
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object Label6: TLabel
          AlignWithMargins = True
          Left = 8
          Top = 42
          Width = 145
          Height = 18
          AutoSize = False
          Caption = 'Ticket..................:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -15
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object lblTicket: TLabel
          Left = 159
          Top = 40
          Width = 200
          Height = 18
          AutoSize = False
          Caption = '0'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -17
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblTempoTotal: TLabel
          Left = 159
          Top = 112
          Width = 300
          Height = 18
          AutoSize = False
          Caption = '0'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -17
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          WordWrap = True
        end
        object Label1: TLabel
          AlignWithMargins = True
          Left = 8
          Top = 112
          Width = 145
          Height = 18
          AutoSize = False
          Caption = 'Tempo Decorrido..:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -15
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
        end
      end
      object Panel1: TPanel
        Left = 479
        Top = 0
        Width = 420
        Height = 165
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        object JvGroupBox1: TJvGroupBox
          AlignWithMargins = True
          Left = 3
          Top = 115
          Width = 414
          Height = 50
          Align = alTop
          Caption = 'Total (Servi'#231'os + Produtos)'
          DefaultHeaderFont = False
          HeaderFont.Charset = DEFAULT_CHARSET
          HeaderFont.Color = clBlack
          HeaderFont.Height = -15
          HeaderFont.Name = 'Tahoma'
          HeaderFont.Style = []
          TabOrder = 0
          object lblTotalPagar: TLabel
            AlignWithMargins = True
            Left = 5
            Top = 23
            Width = 404
            Height = 22
            Align = alClient
            Alignment = taRightJustify
            AutoSize = False
            Caption = '0,00'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -20
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            ExplicitLeft = 7
            ExplicitTop = 25
            ExplicitHeight = 41
          end
        end
        object JvGroupBox2: TJvGroupBox
          AlignWithMargins = True
          Left = 3
          Top = 3
          Width = 414
          Height = 50
          Align = alTop
          Caption = 'Total (Servi'#231'os)'
          DefaultHeaderFont = False
          HeaderFont.Charset = DEFAULT_CHARSET
          HeaderFont.Color = clWhite
          HeaderFont.Height = -15
          HeaderFont.Name = 'Tahoma'
          HeaderFont.Style = []
          TabOrder = 1
          object lblTotalServicos: TLabel
            AlignWithMargins = True
            Left = 5
            Top = 23
            Width = 404
            Height = 22
            Align = alClient
            Alignment = taRightJustify
            AutoSize = False
            Caption = '0,00'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -20
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            ExplicitLeft = 7
            ExplicitTop = 3
          end
        end
        object JvGroupBox3: TJvGroupBox
          AlignWithMargins = True
          Left = 3
          Top = 59
          Width = 414
          Height = 50
          Align = alTop
          Caption = 'Total (Produtos )'
          DefaultHeaderFont = False
          HeaderFont.Charset = DEFAULT_CHARSET
          HeaderFont.Color = clBlack
          HeaderFont.Height = -15
          HeaderFont.Name = 'Tahoma'
          HeaderFont.Style = []
          TabOrder = 2
          object lblTotalProdutos: TLabel
            AlignWithMargins = True
            Left = 5
            Top = 23
            Width = 404
            Height = 22
            Align = alClient
            Alignment = taRightJustify
            AutoSize = False
            Caption = '0,00'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -20
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            ExplicitLeft = 7
            ExplicitTop = 25
            ExplicitHeight = 41
          end
        end
      end
    end
    object pnlLateralEsquerda: TPanel
      Left = 0
      Top = 46
      Width = 905
      Height = 349
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 3
      object GroupBox1: TGroupBox
        AlignWithMargins = True
        Left = 3
        Top = 56
        Width = 899
        Height = 290
        Align = alClient
        Caption = 'Produtos'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -15
        Font.Name = 'Segoe UI'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
        object grdProduto: TJvDBGrid
          AlignWithMargins = True
          Left = 5
          Top = 25
          Width = 859
          Height = 260
          Align = alClient
          DataSource = dsProdutos
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -15
          Font.Name = 'Segoe UI'
          Font.Style = []
          Options = [dgTitles, dgIndicator, dgColumnResize, dgColLines, dgRowLines, dgTabs, dgRowSelect, dgConfirmDelete, dgCancelOnExit, dgTitleClick, dgTitleHotTrack]
          ParentFont = False
          TabOrder = 0
          TitleFont.Charset = DEFAULT_CHARSET
          TitleFont.Color = clBlack
          TitleFont.Height = -15
          TitleFont.Name = 'Segoe UI'
          TitleFont.Style = []
          ScrollBars = ssVertical
          SelectColumnsDialogStrings.Caption = 'Select columns'
          SelectColumnsDialogStrings.OK = '&OK'
          SelectColumnsDialogStrings.NoSelectionWarning = 'At least one column must be visible!'
          EditControls = <>
          RowsHeight = 24
          TitleRowHeight = 27
          Columns = <
            item
              Expanded = False
              FieldName = 'nome_reduzido'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clBlue
              Font.Height = -17
              Font.Name = 'Segoe UI'
              Font.Style = []
              Title.Caption = 'Nome'
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clBlack
              Title.Font.Height = -17
              Title.Font.Name = 'Segoe UI'
              Title.Font.Style = []
              Width = 370
              Visible = True
            end
            item
              Alignment = taCenter
              Expanded = False
              FieldName = 'quantidade'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clBlue
              Font.Height = -17
              Font.Name = 'Segoe UI'
              Font.Style = []
              Title.Alignment = taCenter
              Title.Caption = 'Quantidade'
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clBlack
              Title.Font.Height = -17
              Title.Font.Name = 'Segoe UI'
              Title.Font.Style = []
              Width = 150
              Visible = True
            end
            item
              Expanded = False
              FieldName = 'preco_unit'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clBlue
              Font.Height = -17
              Font.Name = 'Segoe UI'
              Font.Style = []
              Title.Alignment = taCenter
              Title.Caption = 'Pre'#231'o Unit'#225'rio'
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clBlack
              Title.Font.Height = -17
              Title.Font.Name = 'Segoe UI'
              Title.Font.Style = []
              Width = 150
              Visible = True
            end
            item
              Expanded = False
              FieldName = 'total'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clBlue
              Font.Height = -15
              Font.Name = 'Segoe UI'
              Font.Style = []
              Title.Alignment = taCenter
              Title.Caption = 'Total'
              Width = 150
              Visible = True
            end>
        end
        object Panel3: TPanel
          Left = 867
          Top = 22
          Width = 30
          Height = 266
          Align = alRight
          BevelOuter = bvNone
          ParentBackground = False
          TabOrder = 1
          object btnRemoverProduto: TAdvGlowButton
            AlignWithMargins = True
            Left = 3
            Top = 33
            Width = 24
            Height = 24
            Hint = 'Remover produto ou servi'#231'o selecionado'
            Align = alTop
            NotesFont.Charset = DEFAULT_CHARSET
            NotesFont.Color = clWindowText
            NotesFont.Height = -12
            NotesFont.Name = 'Tahoma'
            NotesFont.Style = []
            Picture.Data = {
              89504E470D0A1A0A0000000D4948445200000020000000200806000000737A7A
              F400000006624B474400FF00FF00FFA0BDA79300000237494441545809ED964B
              2F245118864B47C2426B0943E2BA424432AEB1C7CA8EB45F242116426C2C58B3
              1A996426E2BAE33758F486C425212C10B745E379E39C4AA9E8541D5D332221EF
              53EF5755DFF7D6A9EAD278DEF7CF273F8112C7EBB7D39F8511A8856A902ED99C
              C13AAC420E12552F69DBF01C934DFABAA1689592300F79D0C575978BD4A3D009
              3F0CAAC7A897E01CD4AB99596A6560EEAA62640B14F6804F411AA25449C33468
              46B37A1A19F69D5446F71E28E000FF09AEEA6240B3CFF82E28138BA745DA3478
              8437C247D5C4E009286B018FA501BA9EE0167AA058F5137007CAECC323B54387
              563C8127A5498294A9F781B2B0DA39A5C60B3CCE0B475B2C65E8BA0465B7E2BE
              527EF55A8CBF9AB78ADF4052BA22E83748596D2CE1050C99136BC693349B391C
              0C4D0577A89B41DAD726616CA6BDC6BBF1371CD5E7548187A5E32E84E7D31CD0
              FC35EE2BFC04EC1F2735FA4DFFB2082FE0D45CACDE78D0B4381782B3AA1BB481
              13F0155EC09139D3613C49B399C7C1D0F00236CCC951E3499ACDD4FF0C0573FF
              FB17D17B2BD9E6A05EC2093C294D11A44CFB84D92DAC1E4EE5E116546345A99F
              E97B5066171E4B737469C57A291BA93FAA2606F5D62B6B863AB65274FE050D5E
              E083E0AA210634AB8C3FD429705286EE2D50C0033E03D510A51A1A66E11134BB
              892B0B73572923F39007855DE3CB9085362837A81EA75E01F5A8573373EC2B03
              2B4EBD8CDBDF0E8547A1BBEE66265225911D6F1BF43DA1BB1FE1700BD48174C6
              E6D0F3BC0DF80539F8D6D778022F4BDA9119FEEA7CD00000000049454E44AE42
              6082}
            Rounded = True
            Transparent = True
            ParentShowHint = False
            ShowHint = True
            TabOrder = 0
            OnClick = btnRemoverProdutoClick
            Appearance.BorderColor = 11382963
            Appearance.BorderColorHot = 11565130
            Appearance.BorderColorCheckedHot = 11565130
            Appearance.BorderColorDown = 11565130
            Appearance.BorderColorChecked = 13744549
            Appearance.BorderColorDisabled = 13948116
            Appearance.Color = clWhite
            Appearance.ColorTo = clWhite
            Appearance.ColorChecked = 13744549
            Appearance.ColorCheckedTo = 13744549
            Appearance.ColorDisabled = clWhite
            Appearance.ColorDisabledTo = clNone
            Appearance.ColorDown = 11565130
            Appearance.ColorDownTo = 11565130
            Appearance.ColorHot = 16444643
            Appearance.ColorHotTo = 16444643
            Appearance.ColorMirror = clWhite
            Appearance.ColorMirrorTo = clWhite
            Appearance.ColorMirrorHot = 16444643
            Appearance.ColorMirrorHotTo = 16444643
            Appearance.ColorMirrorDown = 11565130
            Appearance.ColorMirrorDownTo = 11565130
            Appearance.ColorMirrorChecked = 13744549
            Appearance.ColorMirrorCheckedTo = 13744549
            Appearance.ColorMirrorDisabled = clWhite
            Appearance.ColorMirrorDisabledTo = clNone
            Appearance.GradientHot = ggVertical
            Appearance.GradientMirrorHot = ggVertical
            Appearance.GradientDown = ggVertical
            Appearance.GradientMirrorDown = ggVertical
            Appearance.GradientChecked = ggVertical
            Appearance.TextColorChecked = 3750459
            Appearance.TextColorDown = 2303013
            Appearance.TextColorHot = 2303013
            Appearance.TextColorDisabled = 13948116
            DropDownWidth = 15
          end
          object btnAdicionarProduto: TAdvGlowButton
            AlignWithMargins = True
            Left = 3
            Top = 3
            Width = 24
            Height = 24
            Hint = 'Inclus'#227'o de produtos e servi'#231'os'
            Align = alTop
            NotesFont.Charset = DEFAULT_CHARSET
            NotesFont.Color = clWindowText
            NotesFont.Height = -12
            NotesFont.Name = 'Tahoma'
            NotesFont.Style = []
            Picture.Data = {
              89504E470D0A1A0A0000000D4948445200000020000000200806000000737A7A
              F400000006624B474400FF00FF00FFA0BDA7930000024B494441545809ED963B
              4B1C511886C765410B7503DEC0A8A9A28810AFD86B2A3B65FD458262218A8D85
              D65A294282784B177F83858D818D8261B788E2ADD8E8F3EA39CB7A703D33EE68
              1094F799F79B33EFF7CDD971BC04C1FBD77F7E021511EFDF413E0D23D0087520
              E5389CC026ACC101C4AA3EA6EDC24D48B6C9F540D94A32611EF2A09BEB532E52
              8F42173418548F512FC11F50563DB3D49A8145D7075A7640C3AEF029A8019F6A
              094C837AD4ABA791E23C922A49EF81061CE25F20AABA6950EF0DFE1334130BA7
              45626ACCE02DF05CB5D278049AB58087D220A97F700EBD50AE061870019AD98F
              7BF58384763C81FBA49CF0E5260928A7F781B2B43AB8A460160FF3C2292B883F
              A9145773A0EC67BCA044A1BA2FC6EF2D58C3CF202EFD65D03A48691D2CEE0686
              CD850DE3719A9DF9B57868A2F884BA0DA47D1D62C6CEB4F77874FC19ABFA3E55
              E3AEB41E05B7BF8605F59FE205B94FC0FE7152B0107AC9C2DDC0B1B959B3F162
              D3E65CEC75775DE7F69AF58FA638327E67EE063277AB41D0693C4EB3337F170F
              7537B0652E8E1A8FD3EC4CFDCF5072EEABFF227A6C27BB2CEA259CC07D524EF8
              72530494B34F98D3D2EAE5521ECE4135569606E8BE04CDECC643698E9476AC97
              B285FAB96AA5516FBD66CD50875682E4775063161F82A81AA641BD9AF18D3A01
              919422BD031A7085CF401DF8544F6016AE41BDDBB86661D195A4651EF2A061A7
              F832A4A11DAA0CAAC7A957401965D533C7B96660E5A98F76FBD3A1E13EF4A97B
              E8F1AAC29B7818D0EF097DFA11963F411348271C7E0541B005AB7000EF7A1B4F
              E016748C990F86B338C80000000049454E44AE426082}
            Rounded = True
            Transparent = True
            ParentShowHint = False
            ShowHint = True
            TabOrder = 1
            OnClick = btnAdicionarProdutoClick
            Appearance.BorderColor = 11382963
            Appearance.BorderColorHot = 11565130
            Appearance.BorderColorCheckedHot = 11565130
            Appearance.BorderColorDown = 11565130
            Appearance.BorderColorChecked = 13744549
            Appearance.BorderColorDisabled = 13948116
            Appearance.Color = clWhite
            Appearance.ColorTo = clWhite
            Appearance.ColorChecked = 13744549
            Appearance.ColorCheckedTo = 13744549
            Appearance.ColorDisabled = clWhite
            Appearance.ColorDisabledTo = clNone
            Appearance.ColorDown = 11565130
            Appearance.ColorDownTo = 11565130
            Appearance.ColorHot = 16444643
            Appearance.ColorHotTo = 16444643
            Appearance.ColorMirror = clWhite
            Appearance.ColorMirrorTo = clWhite
            Appearance.ColorMirrorHot = 16444643
            Appearance.ColorMirrorHotTo = 16444643
            Appearance.ColorMirrorDown = 11565130
            Appearance.ColorMirrorDownTo = 11565130
            Appearance.ColorMirrorChecked = 13744549
            Appearance.ColorMirrorCheckedTo = 13744549
            Appearance.ColorMirrorDisabled = clWhite
            Appearance.ColorMirrorDisabledTo = clNone
            Appearance.GradientHot = ggVertical
            Appearance.GradientMirrorHot = ggVertical
            Appearance.GradientDown = ggVertical
            Appearance.GradientMirrorDown = ggVertical
            Appearance.GradientChecked = ggVertical
            Appearance.TextColorChecked = 3750459
            Appearance.TextColorDown = 2303013
            Appearance.TextColorHot = 2303013
            Appearance.TextColorDisabled = 13948116
            DropDownWidth = 15
          end
        end
      end
      object pnlCliente: TPanel
        AlignWithMargins = True
        Left = 3
        Top = 3
        Width = 899
        Height = 47
        Align = alTop
        TabOrder = 1
        object lblNomeCliente: TLabel
          Left = 10
          Top = 14
          Width = 49
          Height = 20
          Caption = 'Cliente:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -15
          Font.Name = 'Segoe UI'
          Font.Style = []
          ParentFont = False
        end
        object edtCodigoMensalista: TAdvEdit
          Left = 65
          Top = 10
          Width = 100
          Height = 28
          EditType = etNumeric
          EmptyTextStyle = []
          FlatLineColor = 11250603
          FocusColor = clWindow
          FocusFontColor = 3881787
          LabelFont.Charset = DEFAULT_CHARSET
          LabelFont.Color = clWindowText
          LabelFont.Height = -15
          LabelFont.Name = 'Segoe UI'
          LabelFont.Style = []
          Lookup.Font.Charset = DEFAULT_CHARSET
          Lookup.Font.Color = clWhite
          Lookup.Font.Height = -11
          Lookup.Font.Name = 'Segoe UI'
          Lookup.Font.Style = []
          Lookup.Separator = ';'
          CharCase = ecUpperCase
          Color = clWindow
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -15
          Font.Name = 'Segoe UI'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          Text = '0'
          Visible = True
          OnKeyDown = edtCodigoMensalistaKeyDown
          Version = '4.0.5.0'
        end
        object pnlNomeMensalista: TPanel
          Left = 171
          Top = 10
          Width = 685
          Height = 28
          Alignment = taLeftJustify
          BorderWidth = 2
          ParentBackground = False
          TabOrder = 1
        end
        object btnConsultaCliente: TAdvGlowButton
          Left = 862
          Top = 10
          Width = 28
          Height = 28
          Default = True
          NotesFont.Charset = DEFAULT_CHARSET
          NotesFont.Color = clWindowText
          NotesFont.Height = -13
          NotesFont.Name = 'Tahoma'
          NotesFont.Style = []
          Picture.Data = {
            89504E470D0A1A0A0000000D49484452000000100000001008060000001FF3FF
            6100000006624B474400FF00FF00FFA0BDA793000001A4494441543811A5523D
            4BC350146D3EBA9450872A8291829319B44B41D17FE05C2A31D58A8299C41FE3
            A63835AD0D54500BA58E5D1C74D0A1DAA9439046413022C4A53589E73D4AC923
            2815C339B9EF9E7BDFCD7DF72516FBE7C385F7E7F379291E8F6B1CC7AD0EF56B
            9EE74F0DC3F81CFA11332A50281416116D8213E00348B080D7BBEFFB6BD56AF5
            11EB0878A2902FC33640CBF3BCF94AA5B24228088202AD872E1ABAAE27B08E80
            1640DB5B884C82AA699ACFB014A552C9461115CEB4EBBA9BB011D00238F31222
            77F86A0F96018A3C41B847CE326C047C48F1436B6689CD1E23841C5A2008825B
            68590C72169641B1584C239E056F98C0D0A10506838101FF0D3455559D81A5C0
            6619433D87E3489254868D609C6B74B14B049BFD7E7FA756AB31C71110A068B7
            DBAF8AA21CE3CA5E70E60444D2D109FC3DFC076968BBB891B95C2E77D96AB502
            C429461D50EFE717A769DA218AEC23E5CCB6ED0D14F9C23A36EA8038BF111D5E
            65329929E46C27934925954A5D5896E5D321421C0701667080C432B82ECBB20E
            3B7E0724B9D3E90498535D14C50FC7718EBADD2E335092F3677E032DB18AE461
            CC7CD50000000049454E44AE426082}
          Rounded = True
          Transparent = True
          TabOrder = 2
          OnClick = btnConsultaClienteClick
          Appearance.BorderColor = 11382963
          Appearance.BorderColorHot = 11565130
          Appearance.BorderColorCheckedHot = 11565130
          Appearance.BorderColorDown = 11565130
          Appearance.BorderColorChecked = 13744549
          Appearance.BorderColorDisabled = 13948116
          Appearance.Color = clWhite
          Appearance.ColorTo = clWhite
          Appearance.ColorChecked = 13744549
          Appearance.ColorCheckedTo = 13744549
          Appearance.ColorDisabled = clWhite
          Appearance.ColorDisabledTo = clNone
          Appearance.ColorDown = 11565130
          Appearance.ColorDownTo = 11565130
          Appearance.ColorHot = 16444643
          Appearance.ColorHotTo = 16444643
          Appearance.ColorMirror = clWhite
          Appearance.ColorMirrorTo = clWhite
          Appearance.ColorMirrorHot = 16444643
          Appearance.ColorMirrorHotTo = 16444643
          Appearance.ColorMirrorDown = 11565130
          Appearance.ColorMirrorDownTo = 11565130
          Appearance.ColorMirrorChecked = 13744549
          Appearance.ColorMirrorCheckedTo = 13744549
          Appearance.ColorMirrorDisabled = clWhite
          Appearance.ColorMirrorDisabledTo = clNone
          Appearance.GradientHot = ggVertical
          Appearance.GradientMirrorHot = ggVertical
          Appearance.GradientDown = ggVertical
          Appearance.GradientMirrorDown = ggVertical
          Appearance.GradientChecked = ggVertical
          Appearance.TextColorChecked = 3750459
          Appearance.TextColorDown = 2303013
          Appearance.TextColorHot = 2303013
          Appearance.TextColorDisabled = 13948116
        end
      end
    end
  end
  object cdsPagamentos: TClientDataSet
    Aggregates = <>
    FieldDefs = <
      item
        Name = 'id'
        DataType = ftInteger
      end
      item
        Name = 'nome'
        DataType = ftString
        Size = 100
      end
      item
        Name = 'valor'
        DataType = ftFloat
        Precision = 2
      end>
    IndexDefs = <>
    Params = <>
    StoreDefs = True
    Left = 353
    Top = 196
    object cdsPagamentosid: TIntegerField
      FieldName = 'id'
    end
    object cdsPagamentosnome: TStringField
      FieldName = 'nome'
      Size = 100
    end
    object cdsPagamentosvalor: TFloatField
      FieldName = 'valor'
      DisplayFormat = '#,##0.00'
      EditFormat = '#,##0.00'
    end
  end
  object DSPagamentos: TDataSource
    DataSet = cdsPagamentos
    Left = 385
    Top = 196
  end
  object ppmMenuLateral: TAdvPopupMenu
    Version = '2.7.1.12'
    UIStyle = tsWindows8
    Left = 416
    Top = 200
    object mnInserirPagamento: TMenuItem
      Bitmap.Data = {
        F6060000424DF606000000000000360000002800000018000000180000000100
        180000000000C0060000C40E0000C40E00000000000000000000FFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFEFEFFFCFCFFFBFBFFFAFAFFFAFAFFFBFBFFFCFCFFFEFEFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFEFEFFFBFBFFF8F8FFF8F8FFF9F9FFF9F9FFF9F9FFF9F9FFF8F8FF
        F8F8FFFBFBFFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFDFDFFF9F9FFF8F8FFFBFBFFFEFEFFFFFFFFFFFFFFFF
        FFFFFFFFFFFEFEFFFBFBFFF8F8FFF9F9FFFDFDFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFDFFF8F8FFF9F9FFFEFEFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF8F8FFFDFDFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF9F9FFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFF9F9FFF9F9FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFFF8
        F8FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFEFEFFF8F8FFFBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFEFEFFF8F8FFFBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFFFB
        FBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFFF8F8FFFEFEFFFFFFFF
        FFFFFFFFFFFFFFFFFFFCFCFFF8F8FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFAFAFFFAFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF8
        F8FFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFFF9F9FFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFAFAFFFAFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFF9F9FFFBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFAFAFFF9F9FFFF
        FFFFFFFFFFFFFFFFFFFFFFFBFBFFFAFAFFFAFAFFF9F9FFF9F9FFFAFAFFFAFAFF
        FBFBFFFFFFFFFFFFFFFFFFFFFFFFFFF9F9FFFAFAFFFFFFFFFFFFFFFFFFFFFFFF
        FFFAFAFFF9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFFFAFAFFFAFAFFF9F9FFF9
        F9FFFAFAFFFAFAFFFBFBFFFFFFFFFFFFFFFFFFFFFFFFFFF9F9FFFAFAFFFFFFFF
        FFFFFFFFFFFFFFFFFFFBFBFFF9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFAFAFFFAFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9
        F9FFFBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFFF8F8FFFEFEFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFAFAFFFAFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFEFEFFF8F8FFFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF8F8FFFB
        FBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFFFBFBFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFBFBFFF8F8FFFEFEFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFBFBFFF8F8FFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF8F8FFFBFBFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9FFF9F9FFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9F9FFF9F9FFFE
        FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFDFFF8F8FFF9F9FF
        FEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFF9F9
        FFF8F8FFFDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFDFDFFF9F9FFF8F8FFFBFBFFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFF
        FBFBFFF8F8FFF9F9FFFDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFFBFBFFF8F8FFF8F8FFF9F9FFF9F9FFF9
        F9FFF9F9FFF8F8FFF8F8FFFBFBFFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFFFCFC
        FFFBFBFFFAFAFFFAFAFFFBFBFFFCFCFFFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
      Caption = '&Inserir'
    end
    object mnExcluirPagamento: TMenuItem
      Caption = '&Excluir'
    end
  end
  object cdsProdutos: TClientDataSet
    Aggregates = <>
    FieldDefs = <
      item
        Name = 'id'
        DataType = ftInteger
      end
      item
        Name = 'nome_reduzido'
        DataType = ftString
        Size = 100
      end
      item
        Name = 'quantidade'
        DataType = ftInteger
      end
      item
        Name = 'preco_unit'
        DataType = ftFloat
        Precision = 2
      end
      item
        Name = 'tipo'
        DataType = ftInteger
      end
      item
        Name = 'total'
        DataType = ftFloat
      end>
    IndexDefs = <>
    Params = <>
    StoreDefs = True
    OnCalcFields = cdsProdutosCalcFields
    Left = 241
    Top = 172
    object id: TIntegerField
      FieldName = 'id'
    end
    object nome_reduzido: TStringField
      FieldName = 'nome_reduzido'
      Size = 100
    end
    object quantidade: TIntegerField
      DisplayLabel = 'Qtd.'
      FieldName = 'quantidade'
    end
    object preco_unit: TFloatField
      FieldName = 'preco_unit'
      DisplayFormat = '#,##0.00'
      EditFormat = '#,##0.00'
    end
    object tipo: TIntegerField
      FieldName = 'tipo'
    end
    object cdsProdutostotal: TFloatField
      FieldKind = fkCalculated
      FieldName = 'total'
      DisplayFormat = '#,##0.00'
      EditFormat = '#,##0.00'
      Calculated = True
    end
  end
  object dsProdutos: TDataSource
    DataSet = cdsProdutos
    Left = 233
    Top = 220
  end
end
