/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import org.junit.Test;
import model.Veiculo.Cor;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test
    public void testGravaCor() {
    	Cor cor = new Cor();
    	cor.setNome("Azul");
    	
    	cor.save();
    	
    	assertNotNull("Id do objeto está nulo.", cor.getId());
    }
}
