/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.math.BigDecimal;
import org.junit.Test;
import model.Veiculo.Cor;
import model.Veiculo.EnumTipoVeiculo;
import model.Veiculo.MarcaVeiculo;
import model.Veiculo.ModeloVeiculo;
import model.Veiculo.Veiculo;

public class LibraryTest extends BaseTest {

	@Test
	public void testGravaCor() {
		Cor cor = new Cor();
		cor.setNome("Azul");

		cor.save();

		assertNotNull("Id do objeto está nulo.", cor.getId());
	}

	@Test
	public void testGravaVeiculoFull() {
		ModeloVeiculo modelo = new ModeloVeiculo();
		modelo.setNome("2.0 MPFI");
		modelo.save();

		MarcaVeiculo marca = new MarcaVeiculo();
		marca.setNome("Chevrolet");
		marca.save();

		Cor cor = new Cor();
		cor.setNome("Preto");
		cor.save();

		Veiculo veiculo = new Veiculo();
		veiculo.setNome("Vectra");
		veiculo.setMarca(marca);
		veiculo.setModelo(modelo);
		veiculo.setTipoVeiculo(EnumTipoVeiculo.GRANDE);
		veiculo.setCor(cor);
		veiculo.setValor(BigDecimal.valueOf(5.00));

		veiculo.save();

		assertNotNull("Cor do veículo está nulo.", veiculo.getCor().getId());
	}
}
